### ISSUE TITLE
Broken screenshot in Flathub app page

### ISSUE THREAD

**Issue by travier** [flathub/org.kde.kteatime#1]

**Comment by cho2** [comment]
![screenshot-flathub org-2022 05 30-09_54_40](https://user-images.githubusercontent.com/6271071/170908826-3bbdf6cc-91af-4b20-8fb4-232e7da3a52e.png)

Size issue on upstream?

https://cdn.kde.org/screenshots/kteatime/kteatime.png

**Comment by travier** [comment]
Weird, the appdata entry has no size and the image loads in a browser.

**Comment by tsdgeos** [comment]
flatpak/flathub is sometimes unreasonably super opinionated

I can very well see it having some rule saying that 237x336 is too small for a valid screenshot

**Comment by travier** [comment]
LGTM to me now
